export const cuisineList = [
    "Indian",
    "North Indian",
    "Sea-Food",
    "BreakFast",
    "Barbeque",
    "Italian",
    "South Indian",
    "Fast Food",
    "Salads",
    "Burger",
    "American",
    "Punjabi Cuisine",
    "Hyderabadi",
    "Healthy",
    "Pizza",
    "Chinese",
    "Goa Cuisine",
    "Tandoori",
    "Cafe",
    "Snacks",
    "French",
    "Malabari Cuisine",
    "Mexican",
    "Deserts",
    "Beverages",
]